<!-- End Top Background Image Wrapper -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<div class="wrapper row3">
  <main class="hoc container clear">
    <!-- main body -->
    <!-- ################################################################################################ -->
    <div class="content">
      <!-- ################################################################################################ -->
      <div id="gallery">
        <figure>
          <header class="heading">Gallery Title Goes Here</header>
          <ul class="nospace clear">
            <li class="one_quarter">
              <article><a href="http://www.match.com/productbrowser"><img src="<?php echo $this->imgUrl; ?>/320x220.png" alt=""></a>
                <div class="txtwrap">
                  <h6 class="heading">Malesuada posuere</h6>
                  <time datetime="2045-04-06">6<sup>th</sup> April 2045</time>
                  <p>Ante pulvinar hendrerit ipsum ut scelerisque sapien purus sit amet&hellip;</p>
                  <footer><a href="http://www.match.com/productbrowser">Read More &raquo;</a></footer>
                </div>
              </article>
            </li>
            <li class="one_quarter">
              <article><a href="http://www.match.com/productbrowser"><img src="<?php echo $this->imgUrl; ?>/320x220.png" alt=""></a>
                <div class="txtwrap">
                  <h6 class="heading">Malesuada posuere</h6>
                  <time datetime="2045-04-06">6<sup>th</sup> April 2045</time>
                  <p>Ante pulvinar hendrerit ipsum ut scelerisque sapien purus sit amet&hellip;</p>
                  <footer><a href="http://www.match.com/productbrowser">Read More &raquo;</a></footer>
                </div>
              </article>
            </li>
            <li class="one_quarter">
              <article><a href="http://www.match.com/productbrowser"><img src="<?php echo $this->imgUrl; ?>/320x220.png" alt=""></a>
                <div class="txtwrap">
                  <h6 class="heading">Malesuada posuere</h6>
                  <time datetime="2045-04-06">6<sup>th</sup> April 2045</time>
                  <p>Ante pulvinar hendrerit ipsum ut scelerisque sapien purus sit amet&hellip;</p>
                  <footer><a href="http://www.match.com/productbrowser">Read More &raquo;</a></footer>
                </div>
              </article>
            </li>
            <li class="one_quarter">
              <article><a href="http://www.match.com/productbrowser"><img src="<?php echo $this->imgUrl; ?>/320x220.png" alt=""></a>
                <div class="txtwrap">
                  <h6 class="heading">Malesuada posuere</h6>
                  <time datetime="2045-04-06">6<sup>th</sup> April 2045</time>
                  <p>Ante pulvinar hendrerit ipsum ut scelerisque sapien purus sit amet&hellip;</p>
                  <footer><a href="http://www.match.com/productbrowser">Read More &raquo;</a></footer>
                </div>
              </article>
            </li>
            <li class="one_quarter">
              <article><a href="http://www.match.com/productbrowser"><img src="<?php echo $this->imgUrl; ?>/320x220.png" alt=""></a>
                <div class="txtwrap">
                  <h6 class="heading">Malesuada posuere</h6>
                  <time datetime="2045-04-06">6<sup>th</sup> April 2045</time>
                  <p>Ante pulvinar hendrerit ipsum ut scelerisque sapien purus sit amet&hellip;</p>
                  <footer><a href="http://www.match.com/productbrowser">Read More &raquo;</a></footer>
                </div>
              </article>
            </li>
            <li class="one_quarter">
              <article><a href="http://www.match.com/productbrowser"><img src="<?php echo $this->imgUrl; ?>/320x220.png" alt=""></a>
                <div class="txtwrap">
                  <h6 class="heading">Malesuada posuere</h6>
                  <time datetime="2045-04-06">6<sup>th</sup> April 2045</time>
                  <p>Ante pulvinar hendrerit ipsum ut scelerisque sapien purus sit amet&hellip;</p>
                  <footer><a href="http://www.match.com/productbrowser">Read More &raquo;</a></footer>
                </div>
              </article>
            </li>
            <li class="one_quarter">
              <article><a href="http://www.match.com/productbrowser"><img src="<?php echo $this->imgUrl; ?>/320x220.png" alt=""></a>
                <div class="txtwrap">
                  <h6 class="heading">Malesuada posuere</h6>
                  <time datetime="2045-04-06">6<sup>th</sup> April 2045</time>
                  <p>Ante pulvinar hendrerit ipsum ut scelerisque sapien purus sit amet&hellip;</p>
                  <footer><a href="http://www.match.com/productbrowser">Read More &raquo;</a></footer>
                </div>
              </article>
            </li>
            <li class="one_quarter">
              <article><a href="http://www.match.com/productbrowser"><img src="<?php echo $this->imgUrl; ?>/320x220.png" alt=""></a>
                <div class="txtwrap">
                  <h6 class="heading">Malesuada posuere</h6>
                  <time datetime="2045-04-06">6<sup>th</sup> April 2045</time>
                  <p>Ante pulvinar hendrerit ipsum ut scelerisque sapien purus sit amet&hellip;</p>
                  <footer><a href="http://www.match.com/productbrowser">Read More &raquo;</a></footer>
                </div>
              </article>
            </li>
            <li class="one_quarter">
              <article><a href="http://www.match.com/productbrowser"><img src="<?php echo $this->imgUrl; ?>/320x220.png" alt=""></a>
                <div class="txtwrap">
                  <h6 class="heading">Malesuada posuere</h6>
                  <time datetime="2045-04-06">6<sup>th</sup> April 2045</time>
                  <p>Ante pulvinar hendrerit ipsum ut scelerisque sapien purus sit amet&hellip;</p>
                  <footer><a href="http://www.match.com/productbrowser">Read More &raquo;</a></footer>
                </div>
              </article>
            </li>
            <li class="one_quarter">
              <article><a href="http://www.match.com/productbrowser"><img src="<?php echo $this->imgUrl; ?>/320x220.png" alt=""></a>
                <div class="txtwrap">
                  <h6 class="heading">Malesuada posuere</h6>
                  <time datetime="2045-04-06">6<sup>th</sup> April 2045</time>
                  <p>Ante pulvinar hendrerit ipsum ut scelerisque sapien purus sit amet&hellip;</p>
                  <footer><a href="http://www.match.com/productbrowser">Read More &raquo;</a></footer>
                </div>
              </article>
            </li>
            <li class="one_quarter">
              <article><a href="http://www.match.com/productbrowser"><img src="<?php echo $this->imgUrl; ?>/320x220.png" alt=""></a>
                <div class="txtwrap">
                  <h6 class="heading">Malesuada posuere</h6>
                  <time datetime="2045-04-06">6<sup>th</sup> April 2045</time>
                  <p>Ante pulvinar hendrerit ipsum ut scelerisque sapien purus sit amet&hellip;</p>
                  <footer><a href="http://www.match.com/productbrowser">Read More &raquo;</a></footer>
                </div>
              </article>
            </li>
            <li class="one_quarter">
              <article><a href="http://www.match.com/productbrowser"><img src="<?php echo $this->imgUrl; ?>/320x220.png" alt=""></a>
                <div class="txtwrap">
                  <h6 class="heading">Malesuada posuere</h6>
                  <time datetime="2045-04-06">6<sup>th</sup> April 2045</time>
                  <p>Ante pulvinar hendrerit ipsum ut scelerisque sapien purus sit amet&hellip;</p>
                  <footer><a href="http://www.match.com/productbrowser">Read More &raquo;</a></footer>
                </div>
              </article>
            </li>
          </ul>
        </figure>
      </div>
      <!-- ################################################################################################ -->
      <!-- ################################################################################################ -->
      <nav class="pagination">
        <ul>
          <li><a href="#">&laquo; Previous</a></li>
          <li><a href="#">1</a></li>
          <li><a href="#">2</a></li>
          <li><strong>&hellip;</strong></li>
          <li><a href="#">6</a></li>
          <li class="current"><strong>7</strong></li>
          <li><a href="#">8</a></li>
          <li><a href="#">9</a></li>
          <li><strong>&hellip;</strong></li>
          <li><a href="#">14</a></li>
          <li><a href="#">15</a></li>
          <li><a href="#">Next &raquo;</a></li>
        </ul>
      </nav>
      <!-- ################################################################################################ -->
    </div>
    <!-- ################################################################################################ -->
    <!-- / main body -->
    <div class="clear"></div>
  </main>
</div>
