<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Match - 管理画面</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">ログイン <span class="sr-only">(current)</span></a></li>
        <li><a href="#">商品管理</a></li>
        <li><a href="#">履歴</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
  <div class="row">
    <h3 style="text-align: center;">ログイン</h3>
  </div>
  <hr>
  <div class="row">
    <div class="col-sm-4">

    </div>
    <div class="col-sm-4">
      <form>
        <div class="form-group">
          <label>Email address</label>
          <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
        </div>
        <div class="form-group">
          <label>Password</label>
          <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
        </div>
        <div class="checkbox">
          <label>
            <input type="checkbox">　アカウントを保存する
          </label>
        </div>
        <button type="submit" class="btn btn-default">ログイン</button>
      </form>
    </div>
    <div class="col-sm-4">

    </div>
  </div>
</div>
