<div class="wrapper">
  <section class="hoc container clear">
    <div class="content">
      <h1>プロフィール管理</h1>
      <table>
        <tr>
          <td>Avatar</td>
          <td>
            <img style="float: left; margin-right: 20px;height: 80px; width: 80px; object-fit: cover;"
                 src="<?php echo $this->baseUrl($this->user['img']);?>">
          </td>
        </tr>
        <tr>
          <td>Username</td>
          <td><?php echo $this->user['username'] ?></td>
        </tr>
        <tr>
          <td>Email</td>
          <td><?php echo $this->user['email'] ?></td>
        </tr>
        <tr>
          <td>名前</td>
          <td><?php echo $this->user['name'] ?></td>
        </tr>
        <tr>
          <td>性別</td>
          <td><?php
            switch ($this->user['sex']) {
              case 0:
                echo "男";
                break;
              case 1:
                echo "女";
                break;
              default:
                echo "未定";
                break;
            }
          ?></td>
        </tr>
      </table>

      <input class="btn" style="color: #000000;" type="submit" name="change" value="修正">
    </div>
  </section>
</div>
