<?php
  $error = $this->formLabel('error', $this->error, array('style'=>'margin-left: 5px; font-size: 15px;', 'class'=>'label label-danger'));
  $captchaBox = $this->formText('captchaBox', '', array('placeholder'=>'キャプチャを入力', 'class'=>'form-control'));
  $captchaIdHidden = $this->formHidden('captchaId', $this->captcha_id);
  $captcha = '<span id="captcha-container" style="display:inline-block; margin: 5px;">' . $this->captcha . '</span>';
?>
<form action="" method="post">
  <div class="form-group">
    <label>Username</label>
    <input type="text" name="username" class="form-control" id="username" placeholder="Username"
        value='<?php if (isset($_POST["username"])) echo $_POST["username"];?>'>
  </div>
  <div class="form-group">
    <label>Password</label>
    <input type="password" name="password" class="form-control" id="password" placeholder="Password"
        value='<?php if (isset($_POST["password"])) echo $_POST["password"];?>'>
  </div>
  <div class="form-group">
    <label>Confirm Password</label>
    <input type="password" name="repassword" class="form-control" id="repassword" placeholder="Confirm Password"
        value='<?php if (isset($_POST["repassword"])) echo $_POST["repassword"];?>'>
  </div>
  <?php echo $captcha . $captchaBox . $captchaIdHidden; ?>
  <hr>
  <input type="submit" name="submit" class="btn btn-default" value="確認"/>
  <?php echo $error; ?>
</form>
