<div class="wrapper row3">
  <section class="hoc container clear">
    <!-- ################################################################################################ -->
    <div class="center btmspace-50">
      <h2 class="heading">気になるような商品</h2>
    </div>
    <ul class="nospace elements">
      <?php foreach($this->recommendation as $r):?>
        <li class="one_quarter">
          <article>
            <a href="<?php echo $this->baseUrl('product/detail/idcat/' . $r['idCat'] . '/page/1/id/' . $r['id']); ?>">
              <img src="<?php echo $r['img']; ?>">
            </a>
            <div class="txtwrap">
              <p class="textProductName"><?php echo $r['name']; ?></p>
              <footer><a href="<?php echo $this->baseUrl('product/detail/idcat/' . $r['idCat'] . '/page/1/id/' . $r['id']); ?>">Read More &raquo;</a></footer>
            </div>
          </article>
        </li>
      <?php endforeach; ?>
    </ul>
    <!-- ################################################################################################ -->
  </section>
</div>
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
