<div class="wrapper row3">
  <section class="hoc container clear">
    <!-- ################################################################################################ -->
    <div class="center btmspace-50">
      <h2 class="heading">気になるような商品</h2>
    </div>
    <ul class="nospace elements">
      <li class="one_third first">
        <article><a href="http://www.match.com/productbrowser"><img src="images/320x220.png" alt=""></a>
          <div class="txtwrap">
            <h6 class="heading">Malesuada posuere</h6>
            <time datetime="2045-04-06">6<sup>th</sup> April 2045</time>
            <p>Ante pulvinar hendrerit ipsum ut scelerisque sapien purus sit amet&hellip;</p>
            <footer><a href="http://www.match.com/productbrowser">Read More &raquo;</a></footer>
          </div>
        </article>
      </li>
      <li class="one_third">
        <article><a href="http://www.match.com/productbrowser"><img src="images/320x220.png" alt=""></a>
          <div class="txtwrap">
            <h6 class="heading">Vivamus sit amet</h6>
            <time datetime="2045-04-05">5<sup>th</sup> April 2045</time>
            <p>Sagittis in aenean porta semper tortor vel blandit magna integer ac&hellip;</p>
            <footer><a href="http://www.match.com/productbrowser">Read More &raquo;</a></footer>
          </div>
        </article>
      </li>
      <li class="one_third">
        <article><a href="http://www.match.com/productbrowser"><img src="images/320x220.png" alt=""></a>
          <div class="txtwrap">
            <h6 class="heading">Pulvinar nisl non</h6>
            <time datetime="2045-04-04">4<sup>th</sup> April 2045</time>
            <p>Neque malesuada euismod proin sit amet nisl velit mauris orci nisl&hellip;</p>
            <footer><a href="http://www.match.com/productbrowser">Read More &raquo;</a></footer>
          </div>
        </article>
      </li>
    </ul>
    <!-- ################################################################################################ -->
  </section>
</div>
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
