<div class="wrapper">
  <section class="hoc container clear">
    <div class="content">
      <h1>プロフィール管理</h1>
      <table>
        <tr>
          <td>Avatar</td>
          <td>
            <div class="form-group" style="overflow:auto; margin: 0;">
              <img style="float: left; margin-right: 20px;" src="images/80x80.png">
              <input type="file" value="修正"/>
            </div>
          </td>
        </tr>
        <tr>
          <td>Username</td>
          <td>nguyen.huu.ngoc@elife.co.jp</td>
        </tr>
        <tr>
          <td>Password</td>
          <td>
            <label style="float: left; margin-right: 20px;">******</label>
            <button type="button" name="button">修正</button>
          </td>
        </tr>
        <tr>
          <td>名前</td>
          <td>ゴック</td>
        </tr>
        <tr>
          <td>名字</td>
          <td>グエン　フー</td>
        </tr>
        <tr>
          <td>生年月日</td>
          <td>1993/07/02</td>
        </tr>
        <tr>
          <td>性別</td>
          <td>男</td>
        </tr>
      </table>
    </div>
  </section>
</div>
