<form action="" method="post">
  <div class="form-group">
    <label>Username</label>
    <?php echo $this->formText('username', "", array("class"=>"form-control", "placeholder"=>"Username")) ?>
  </div>
  <div class="form-group">
    <label>Password</label>
    <?php echo $this->formPassword('password', "", array("class" => "form-control", "placeholder"=>"Password")); ?>
  </div>
  <div class="checkbox">
    <label>
      <input type="checkbox" name='remember' id='remember'>　アカウントを保存する
    </label>
  </div>
  <?php echo $this->formSubmit('submit', 'ログイン', array('class'=>'btn btn-default')); ?>
  <span class="label label-danger"><?php echo $this->notation; ?></span>
</form>
