<form>
  <div class="form-group">
    <label>Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
  </div>
  <div class="form-group">
    <label>Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <div class="checkbox">
    <label>
      <input type="checkbox">　アカウントを保存する
    </label>
  </div>
  <button type="submit" class="btn btn-default">ログイン</button>
</form>
