<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="<?php echo $this->baseUrl('admin/index/index'); ?>">Match - 管理画面</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <?php if ($this->arrayParams['controller'] == 'product'): ?>
          <li><a href="<?php echo $this->baseUrl('admin/index'); ?>">アカウント</a></li>
          <li class="active"><a href="<?php echo $this->baseUrl('admin/product/index/idcat/19/page/1'); ?>">商品管理</a></li>
          <li><a href="<?php echo $this->baseUrl('admin/history'); ?>">履歴</a></li>
        <?php elseif($this->arrayParams['controller'] == 'index'): ?>
          <li class="active"><a href="<?php echo $this->baseUrl('admin/index'); ?>">アカウント</a></li>
          <li><a href="<?php echo $this->baseUrl('admin/product/index/idcat/19/page/1'); ?>">商品管理</a></li>
          <li><a href="<?php echo $this->baseUrl('admin/history'); ?>">履歴</a></li>
        <?php elseif($this->arrayParams['controller'] == 'history'): ?>
          <li><a href="<?php echo $this->baseUrl('admin/index'); ?>">アカウント</a></li>
          <li><a href="<?php echo $this->baseUrl('admin/product/index/idcat/19/page/1'); ?>">商品管理</a></li>
          <li class="active"><a href="<?php echo $this->baseUrl('admin/history'); ?>">履歴</a></li>
        <?php endif; ?>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><a href="<?php echo $this->baseUrl('admin/product/insert'); ?>"><img src="./images/add.png" alt=""></a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
