<div class="wrapper overlay">
  <header id="header" class="hoc clear">
    <nav id="mainav" class="clear">
      <!-- ################################################################################################ -->
      <ul class="clear">
        <li class="active"><a href="<?php echo $this->baseUrl('index/index'); ?>">ホーム</a></li>
        <li><a href="<?php echo $this->baseUrl('product/list/idcat/19/page/1'); ?>">商品一覧</a></li>
        <?php if ($this->loggedIn): ?>
          <li><a href="<?php echo $this->baseUrl('user/profile'); ?>">プロフィール</a></li>
          <li><a href="<?php echo $this->baseUrl('auth/logout'); ?>">ログアウト</a></li>
        <?php else: ?>
          <li><a onclick="login()">ログイン</a></li>
        <?php endif; ?>
      </ul>
      <!-- ################################################################################################ -->
    </nav>
    <div id="logo">
      <!-- ################################################################################################ -->
      <h1><a href="<?php echo $this->baseUrl('/index'); ?>">Match</a></h1>
      <p>find anything you think about</p>
      <!-- ################################################################################################ -->
    </div>
  </header>
</div>
