<?php
  $idUser = $this->currentUser->id;
  $idProduct = $this->arrayParams['id'];

  if ($this->currentUser !== null) {
      $this->userProductModel->insertNewRelation($idUser, $idProduct);
  }
?>
<div class="wrapper row3">
  <main class="hoc container clear">
    <!-- main body -->
    <div class="content">
      <!-- ################################################################################################ -->
      <h1>商品の情報</h1><hr>
      <div style="display: inline-block; width: 100%; text-align: center;">
        <img style="height:400px; width:400px;" src="<?php echo $this->productInfo['img']; ?>" alt="">
      </div>
      <div style="display: inline-block; text-align: center; width: 100%; margin-top: 20px;">
        <h1 style="display: inline-block; width: 70%; color: #000;"><?php echo $this->productInfo['name']; ?></h1>
      </div>
      <div style="display: inline-block; margin-top: 30px;" class="product-description">
        <?php echo $this->productInfo['description'] ?>
      </div>
      <hr>

      <div id="comments">
        <h2>Comments</h2>
        <ul id="comments-list">
          <?php
            foreach($this->comments as $item):
              $commentedUser = $this->userModel->getUserById($item['idUser']);
          ?>
          <li>
            <article>
              <header>
                <figure class="avatar"><img style="height:32px; width:32px;object-fit:cover;" src="<?php echo $commentedUser['img']; ?>" alt=""></figure>
                <div class="like-block">
                  <a onclick="like(this, '<?php echo $this->baseUrl('ajax/like/id-comment/') . $items['id']; ?>',<?php echo $item['id']; ?>,$('#<?php echo 'likesTag' . $item['id'];?>'))">Likes</a>:
                  <span id="<?php echo 'likesTag' . $item['id'];?>"><?php echo $item['likes']; ?></span>
                </div>
                <address>
                By <a><?php echo $commentedUser['name']; ?></a> (<?php echo $commentedUser['email'];?>)
                </address>
                <small><?php echo $item['time']; ?></small>
              </header>
              <div class="comcont">
                <p><?php echo $item['content']; ?></p>
              </div>
              <hr>
              <button id="btnReplyToggle<?php echo $item['id']; ?>" onclick="replyToggle($('#btnReplyToggle<?php echo $item['id']; ?>'), $('#reply<?php echo $item['id']; ?>'))"
                      class="btn btn-normal" type="button" name="reply" style="padding:8px 16px; color:#000; margin-bottom:10px; font-zise:12px;">reply</button>
              <button id="btnToggle<?php echo $item['id']; ?>" onclick="subCommentToggle($('#btnToggle<?php echo $item['id']; ?>'), $('#sub-comment<?php echo $item['id']; ?>'))"
                      class="btn btn-normal" type="button" name="reply" style="padding:8px 16px; color:#000; margin-bottom:10px; font-zise:12px;">show</button>

              <div id="sub-comment<?php echo $item['id']; ?>" style="display: none;">
                <?php
                  $subComments = $this->subCommentModel->getSubCommentsByComment($item['id']);
                  foreach($subComments as $sub):
                ?>
                    <blockquote style="margin-left:20px; font-size:14px;">
                      <p><?php echo $sub['content']; ?></p>
                      <footer>At <b><cite title="Source Title"><?php echo $sub['time']; ?></cite></b> by <b><cite title="Source Title"><?php echo $sub['name']; ?></cite></b> ( <?php echo $sub['email']; ?> )</footer>
                    </blockquote>
                <?php endforeach; ?>
              </div>

              <div id="reply<?php echo $item['id']; ?>" class="block clear" style="display: none;">
                <?php if ($this->loggedIn): ?>
                  <label for="comment">Your Reply</label>
                  <textarea name="comment" id="comment<?php echo $item['id']; ?>" rows="3"></textarea>
                  <button onclick="addSubComment('<?php echo $this->baseUrl('ajax/add-sub-comment');?>', $('#reply<?php echo $item['id']; ?>'), $('#comment<?php echo $item['id']; ?>'), <?php echo $idUser; ?>, <?php echo $item['id']; ?>)"
                          type="button" name="button" style="margin-top: 5px;">Reply</button>
                <?php else: ?>
                  <span style="color:#f00;">コメントの投稿はログインが必要です。</span>
                <?php endif; ?>
              </div>

            </article>
          </li>
          <?php endforeach; ?>
        </ul>

        <?php if ($this->loggedIn): ?>
          <h2>Write A Comment</h2>
          <div>
            <div class="block clear">
              <label for="comment">Your Comment</label>
              <textarea name="comment" id="comment" cols="25" rows="10"></textarea>
            </div>
            <div>
              <input type="submit" id="submit" value="Add Comment"
                    onclick="addComment('<?php echo $this->baseUrl('ajax/add-comment'); ?>', <?php echo $idUser; ?>, <?php echo $idProduct; ?>)">
            </div>
          </div>
        <?php else: ?>
          <h1 style="color:#f00;">コメントの投稿はログインが必要です。</h1>
        <?php endif; ?>
      </div>
      <!-- ################################################################################################ -->
    </div>
    <!-- ################################################################################################ -->
    <!-- / main body -->
    <hr>
    <div class="wrapper row3">
      <section class="hoc clear">
        <!-- ################################################################################################ -->
        <div class="center">
          <h2 class="heading">これと関係のある商品</h2>
        </div>
        <ul class="nospace elements">
          <?php foreach($this->relation as $r):?>
            <li class="one_quarter">
              <article>
                <a href="<?php echo $this->baseUrl('product/detail/idcat/' . $r['idCat'] . '/page/1/id/' . $r['id']); ?>">
                  <img src="<?php echo $r['img']; ?>">
                </a>
                <div class="txtwrap">
                  <p class="textProductName"><?php echo $r['name']; ?></p>
                  <footer><a href="<?php echo $this->baseUrl('product/detail/idcat/' . $r['idCat'] . '/page/1/id/' . $r['id']); ?>">Read More &raquo;</a></footer>
                </div>
              </article>
            </li>
          <?php endforeach; ?>
        </ul>
        <!-- ################################################################################################ -->
      </section>
    </div>
  </main>
</div>
