<?php
  $idUser = $this->currentUser->id;
  $idProduct = $this->arrayParams['id'];
?>
<div class="wrapper row3">
  <main class="hoc container clear">
    <!-- main body -->
    <div class="content">
      <!-- ################################################################################################ -->
      <h1>商品の情報</h1><hr>
      <div style="display: inline-block; width: 100%; text-align: center;">
        <img style="height:auto; width:auto;" src="<?php echo $this->productInfo['img']; ?>" alt="">
      </div>
      <div style="display: inline-block; text-align: center; width: 100%; margin-top: 20px;">
        <h1 style="display: inline-block; width: 70%; color: #000;"><?php echo $this->productInfo['name']; ?></h1>
      </div>
      <div style="display: inline-block; margin-top: 30px;" class="product-description">
        <?php echo $this->productInfo['description'] ?>
      </div>
      <hr>

      <div id="comments">
        <h2>Comments</h2>
        <ul id="comments-list">
          <?php
            foreach($this->comments as $item):
              $commentedUser = $this->userModel->getUserById($item['idUser']);
          ?>
          <li>
            <article>
              <header>
                <figure class="avatar"><img style="height:32px; width:32px;object-fit:cover;" src="<?php echo $commentedUser['img']; ?>" alt=""></figure>
                <div class="like-block">
                  <a onclick="like(this, '<?php echo $this->baseUrl('ajax/like/id-comment/') . $items['id']; ?>',<?php echo $item['id']; ?>,$('#<?php echo 'likesTag' . $item['id'];?>'))">Likes</a>: <span id="<?php echo 'likesTag' . $item['id'];?>"><?php echo $item['likes']; ?></span>
                </div>
                <address>
                By <a><?php echo $commentedUser['name']; ?></a> (<?php echo $commentedUser['email'];?>)
                </address>
                <small><?php echo $item['time']; ?></small>
              </header>
              <div class="comcont">
                <p><?php echo $item['content']; ?></p>
              </div>
            </article>
          </li>
          <?php endforeach; ?>
        </ul>

        <?php if ($this->loggedIn): ?>
          <h2>Write A Comment</h2>
          <div>
            <div class="block clear">
              <label for="comment">Your Comment</label>
              <textarea name="comment" id="comment" cols="25" rows="10"></textarea>
            </div>
            <div>
              <input type="submit" id="submit" value="Add Comment"
                    onclick="addComment('<?php echo $this->baseUrl('ajax/add-comment'); ?>', <?php echo $idUser; ?>, <?php echo $idProduct; ?>)">
            </div>
          </div>
        <?php else: ?>
          <h1 style="color:#f00;">コメントの投稿はログインが必要です。</h1>
        <?php endif; ?>
      </div>
      <!-- ################################################################################################ -->
    </div>
    <!-- ################################################################################################ -->
    <!-- / main body -->
    <div class="clear"></div>
  </main>
</div>
