<div class="wrapper row3">
  <main class="hoc container clear">
    <!-- main body -->
    <!-- ################################################################################################ -->
    <div class="sidebar one_quarter first">
      <!-- ################################################################################################ -->
      <h6>カテゴリー</h6>
      <nav class="sdb_holder">
        <ul>
          <?php for($i=0; $i<sizeof($this->categoriesData); $i++): ?>
            <li><a href="#"><?php echo $this->categoriesData[$i]['name']; ?></a></li>
          <?php endfor; ?>
        </ul>
      </nav>
      <!-- ################################################################################################ -->
    </div>

    <div class="content three_quarter">
      <!-- ################################################################################################ -->
      <div id="gallery">
        <figure>
          <header class="heading">Gallery Title Goes Here</header>
          <ul class="nospace clear">
            <?php
              for ($i = 0; $i<12; $i++) :
            ?>
            <li class="one_third">
              <article class="product-case"><a href="<?php echo $this->baseUrl("product/detail/id/" . $this->productData[$i]['id']); ?>">
                <img src="<?php echo $this->productData[$i][img]; ?>"></a>
                <div class="txtwrap">
                  <h6 class="heading product-name"><?php echo $this->productData[$i]["name"]; ?></h6>
                  <footer><a href="<?php echo $this->baseUrl("product/detail/id/" . $this->productData[$i]['id']); ?>">Read More &raquo;</a></footer>
                </div>
              </article>
            </li>
            <?php endfor; ?>
          </ul>
        </figure>
      </div>
      <!-- ################################################################################################ -->
      <!-- ################################################################################################ -->
      <nav class="pagination">
        <ul>
          <li><a href="#">&laquo; Previous</a></li>
          <li><a href="#">1</a></li>
          <li><a href="#">2</a></li>
          <li><strong>&hellip;</strong></li>
          <li><a href="#">6</a></li>
          <li class="current"><strong>7</strong></li>
          <li><a href="#">8</a></li>
          <li><a href="#">9</a></li>
          <li><strong>&hellip;</strong></li>
          <li><a href="#">14</a></li>
          <li><a href="#">15</a></li>
          <li><a href="#">Next &raquo;</a></li>
        </ul>
      </nav>
      <!-- ################################################################################################ -->
    </div>
    <!-- ################################################################################################ -->
    <!-- / main body -->
    <div class="clear"></div>
  </main>
</div>
