<?php
$url = $this->baseUrl($this->arrayParams["controller"] . "/" . $this->arrayParams["action"] . "/idcat/");
$urlLinkDetail = $this->baseUrl($this->arrayParams["controller"] . "/detail/idcat/" . $this->arrayParams["idcat"] . "/page/" . $this->arrayParams["page"] . "/id/");
$currentCategory = null;
?>
<div class="wrapper row3">
  <main class="hoc container clear">
    <!-- main body -->
    <!-- ################################################################################################ -->
    <div class="sidebar one_quarter first">
      <!-- ################################################################################################ -->
      <h6>カテゴリー</h6>
      <nav class="sdb_holder">
        <ul>
          <?php
            for($i=0; $i<sizeof($this->categoriesData); $i++):
              if($this->categoriesData[$i]['id'] == $this->arrayParams["idcat"]):
                $currentCategory = $this->categoriesData[$i]['name'];
          ?>
                <li><a style="color:#f00;" href="<?php echo $url . $this->categoriesData[$i]['id'] . "/page/1"; ?>"><?php echo $this->categoriesData[$i]['name']; ?></a></li>
          <?php
              else:
          ?>
                <li><a href="<?php echo $url . $this->categoriesData[$i]['id'] . "/page/1"; ?>"><?php echo $this->categoriesData[$i]['name']; ?></a></li>
          <?php
              endif;
            endfor;
          ?>
        </ul>
      </nav>
      <!-- ################################################################################################ -->
    </div>

    <div class="content three_quarter">
      <!-- ################################################################################################ -->
      <div id="gallery">
        <figure>
          <header class="heading">商品一覧 ( <?php echo $currentCategory; ?> )</header>
          <ul class="nospace clear">
            <?php
              for ($i = 0; $i<count($this->productData); $i++) :
            ?>
            <li class="one_third">
              <article class="product-case"><a href="<?php echo $urlLinkDetail . $this->productData[$i]['id']; ?>">
                <img src="<?php echo $this->productData[$i][img]; ?>"></a>
                <div class="txtwrap">
                  <h6 class="heading product-name"><?php echo $this->productData[$i]["name"]; ?></h6>
                  <footer><a href="<?php echo $urlLinkDetail . $this->productData[$i]['id']; ?>">Read More &raquo;</a></footer>
                </div>
              </article>
            </li>
            <?php endfor; ?>
          </ul>
        </figure>
      </div>
      <!-- ################################################################################################ -->
      <!-- ################################################################################################ -->
      <nav class="pagination">
        <?php
          echo $this->paginationControl($this->paginator, 'Sliding', 'paginator.phtml', array("url"=>$url . $this->arrayParams["idcat"] . "/page/"));
        ?>
      </nav>
      <!-- ################################################################################################ -->
    </div>
    <!-- ################################################################################################ -->
    <!-- / main body -->
    <div class="clear"></div>
  </main>
</div>
