<div class="container" style="padding: 10px 0px;">
  <h1 style="text-align: center;">新商品追加</h1>
  <hr>
  <form method="post" action="" style="padding: 0px 10%;" enctype="multipart/form-data">
    <div class="form-group">
      <label>品名</label>
      <input type="text" class="form-control" name="name" placeholder="品名">
    </div>

    <div class="form-group">
      <label>詳細</label>
      <textarea name="description" id="description" rows="10" cols="80">
      </textarea>
      <script>
        CKEDITOR.replace( 'description' );
      </script>
    </div>

    <div class="form-group">
      <label>種類</label>
      <select class="form-control" name="category">
        <?php foreach($this->categoriesData as $c):?>
          <option value="<?php echo $c['id'] ?>"><?php echo $c['name']; ?></option>
        <?php endforeach; ?>
      </select>
    </div>

    <div class="form-group">
      <label>画像</label>
      <img style="height: 200px; width: 200px; object-fit: cover;" id="imgAvatar">
      <input onchange="updateImage(this)" type="file" name="product" class="form-control"
               style="float: right; width: 60%;">
    </div>

    <hr>
    <button type="submit" class="btn btn-default">追加</button>
  </form>
</div>
