<div class="wrapper row3">
  <main class="hoc container clear">
    <!-- main body -->
    <div class="content">
      <!-- ################################################################################################ -->
      <h1>商品の情報</h1><hr>
      <div style="display: inline-block; width: 100%; text-align: center;">
        <img style="height:400px; width:400px; object-fit: cover;" src="<?php echo $this->productInfo['img']; ?>" alt="">
      </div>
      <div style="display: inline-block; text-align: center; width: 100%; margin-top: 20px;">
        <h1 style="display: inline-block; width: 70%; color: #000;"><?php echo $this->productInfo['name']; ?></h1>
      </div>
      <div style="display: inline-block; margin-top: 30px;" class="product-description">
        <?php echo $this->productInfo['description'] ?>
      </div>
    </div>
  </main>
</div>
