<div id="loginModal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog login-content-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">ログイン</h4>
      </div>
      <div class="modal-body">
        <iframe class="login-ifame" src="http://www.match.com/login"></iframe>
      </div>
      <div class="modal-footer">
        <a onclick="createAccount()">新アカウントを作る</a>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
